#spring:
#  datasource:
#     name: prod
#     url: jdbc:mysql://mysql-kangjian.v2.tenxapp.com:36427/mama-bike
#     username: root
#     password: tenxcloud
#
##activeMQ
#  activemq:
#      broker-url: tcp://activemq-kangjian.v2.tenxapp.com:11890
#      pool:
#        enabled: false
##springdata
#  data:
#     # mongoDB    #mongodb note:mongo3.x will not use host and port,only use uri
#    mongodb:
#      uri: mongodb://mongodb-kangjian.v2.tenxapp.com:19109/mama-bike
#
##reids
#redis:
#    host: redis-kangjian.v2.tenxapp.com
#    port: 51920
#    auth: kangjian
#    max-idle: 5
#    max-total: 10
#    max-wait-millis: 3000

spring:
  datasource:
     name: dev
     url: jdbc:mysql://47.94.216.99:3306/byle
     username: root
     password: m15310614196


redis:
    host: 47.94.216.99
    port: 6379
#    auth: root
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000

#activeMQ
activemq:
   broker-url: tcp://47.94.216.99:61616
   pool:
    enabled: false